### PR TITLE
Various minor tweaks.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by captainsafia** [comment]
Thanks for the cleanup! Mind rebasing? I merged another PR where the image file was removed.

**Comment by XhmikosR** [comment]
Will do later or tomorrow.

**Comment by XhmikosR** [comment]
Please check now.

**Comment by XhmikosR** [comment]
Rebased again. Please don't merge other stuff before merging this :)

**Comment by XhmikosR** [comment]
I added one more patch which switches to ES6 syntax. Let me know if you don't want that so that I rebase and skip it.

**Pull request closed without merging**
